# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60e2c27b1a4847c0aa01e740bb7cc0d7abed36dd78da6451d6047bfe453b47f02b1f44f4cc9ff494887c2f0983dc3036c42667150e46121fd39c48cd09e2039

test:
  secret_key_base: 1160f615d3bc183707bb1db5ea7cfef1519d7406485e4cf9a14acd338bebc7093a29dd792cfd429035dad85f0047dddea6b081009a4ed48f2d214f0980d8407e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
